### ISSUE TITLE
Sapphire Rings & Necklace doesn't work.

### ISSUE THREAD

**Issue by Aqade** [jimathy/jim-mining#12]
Hello @jimathy,

So I've been setting everything up as it should, with everything added to both the "shared.lua" and images in the inventory.

So when I Collect the stones I crack them to get materials. No problem there. I can even get som sapphire, from it.

But here's the problem.

Whenever I have a sapphire uncutted, I cut it, so it can be used to the rings and necklace.
So when I've done that. I try to make the ring or the necklace and I get this error in the F8 console.
![image](https://user-images.githubusercontent.com/64874485/165983433-9e6060d1-46bc-4f92-8e33-a235fe5bb03c.png)

And yes, running the lastest qbcore, if that could be the problem.
But it shouldn't be, since every other gem works fine, its only that one gem, that doesn't.

This does not happend with any of the other gems. Only sapphire.
I haven't changed anything, from what I just got here on github.

**Comment by jimathy** [comment]
From those errors, I think I know the issue. I'll look into a way to fix it

**Comment by Aqade** [comment]
> There, try the latest commit and see if that fixes it

Yup, that seems to fix the problem.
- Thank you for the quick reply and help.

Great job on the script. ;)
