### ISSUE TITLE
Falling threw map

### ISSUE THREAD

**Issue by QBLes** [jimathy/jim-mining#23]
So i noticed sometimes when people goldpan and also cutting/making jewls it makes the users fall threw the map, they are still there in there eyes but in other peoples eyes they keep falling threw then popping back up, also many people have also said they can not talk or hear others once they fall threw the map.

Also a suggestion maybe add more props (drill benches) for cracking / cutting as we have up to 10 people inside each other sometimes using the drilles :P

Cheers bro.

**Comment by jimathy** [comment]
So the props, I could easily do..and so could you lol. But I don’t want to many in one location

The falling through the map is a weird one. I’ve seen things like that happen with broken vehicles but never seen it in my scripts..I’ll keep an eye on what could cause it
