### ISSUE TITLE
not sure but game crashed in foundry 

### ISSUE THREAD

**Issue by yace0** [jimathy/jim-mining#24]
[   script:jim-mining] SCRIPT ERROR: @jim-mining/server.lua:24: attempt to index a nil value
[   script:jim-mining] > TriggerCallback (@qb-core/server/functions.lua:219)
[   script:jim-mining] > handler (@qb-core/server/events.lua:119)
[      script:qb-core] SCRIPT ERROR: error object is not a string

**Comment by QBLes** [comment]
game also crashes at both mine sites, we have probly 30+ people doing this all the time.. nothing but constant crashing..
