### ISSUE TITLE
basically duping of items

### ISSUE THREAD

**Issue by GurkirpalMultani** [jimathy/jim-mining#3]
if you are going near crafting table to craft gold rings you can only use 1 goldbar to make unlimited rings just press tab instantly after selecting the thing you want to craft and then drag the stuff to ground ! this glitch works in everywhere progressbar is used but not at selling because in selling item is removed first and then progressbar comes out but in crafting / mining / even melting this works just press tab instantly after selecting

**Comment by jimathy** [comment]
But..this isn't something I can fix, its an issue with progress bar. You basically telling everyone who to do it lol

**Comment by GurkirpalMultani** [comment]
yes its a progress bar issue but if the same thing happens when selling it happens during crafting then it solve the problem
