### ISSUE TITLE
Problem with Jim-mining

### ISSUE THREAD

**Issue by AlexBanz** [jimathy/jim-mining#31]
![jim](https://user-images.githubusercontent.com/116475136/197372753-227ec34d-fa64-4091-8d0b-4abfafbfe6db.png)
https://github.com/darkosiel/jim-mining

**Comment by Matetv** [comment]
You can read it here! You still need nh-context!

**Comment by jimathy** [comment]
What? Are you telling me to add support for nh-context or are you confused why changing a dependency doesn’t change the entire script

**Comment by jimathy** [comment]
You linked a fork of my script, ask them if you want changes. Otherwise download the updated version from my github

> ![jim](https://user-images.githubusercontent.com/116475136/197372753-227ec34d-fa64-4091-8d0b-4abfafbfe6db.png) https://github.com/darkosiel/jim-mining
