### ISSUE TITLE
Problems installing the script

### ISSUE THREAD

**Issue by Jxelsw** [jimathy/jim-mining#56]
I have followed everything as in the readme and let the script start only after the [qb] folder

nevertheless the script does not work as it should and there are always timeout errors in the f8 console and the blips always alternate after each restart. 

what i want to say with this is sometimes the quarry blip is displayed (where the functions then also don't work)
and sometimes the melt blip and then the quarry blip is gone again 

Timeout errors:

[     82219] [b2699_GTAProce]             MainThrd/ ^5Debug^7: ^3LoadModel^7: ^2Timed out loading model ^7'^6k4mb1_leadore2^7'
[     99797] [b2699_GTAProce]             MainThrd/ ^5Debug^7: ^3LoadModel^7: ^2Timed out loading model ^7'^6k4mb1_emptyore2^7'
[    115656] [b2699_GTAProce]             MainThrd/ ^5Debug^7: ^3LoadModel^7: ^2Timed out loading model ^7'^6k4mb1_crystalblue^7'
[    131938] [b2699_GTAProce]             MainThrd/ ^5Debug^7: ^3LoadModel^7: ^2Timed out loading model ^7'^6k4mb1_crystalempty^7'
[    149578] [b2699_GTAProce]             MainThrd/ ^5Debug^7: ^3LoadModel^7: ^2Timed out loading model ^7'^6k4mb1_tinore2^7'
[    167547] [b2699_GTAProce]             MainThrd/ ^5Debug^7: ^3LoadModel^7: ^2Timed out loading model ^7'^6k4mb1_emptyore2^7'
[    186141] [b2699_GTAProce]             MainThrd/ ^5Debug^7: ^3LoadModel^7: ^2Timed out loading model ^7'^6k4mb1_copperore2^7'
[    204891] [b2699_GTAProce]             MainThrd/ ^5Debug^7: ^3LoadModel^7: ^2Timed out loading model ^7'^6k4mb1_emptyore2^7'
[    222906] [b2699_GTAProce]             MainThrd/ ^5Debug^7: ^3LoadModel^7: ^2Timed out loading model ^7'^6k4mb1_crystalred^7'
[    241531] [b2699_GTAProce]             MainThrd/ ^5Debug^7: ^3LoadModel^7: ^2Timed out loading model ^7'^6k4mb1_crystalempty^7'

**Comment by Jxelsw** [comment]
![FiveM_b2699_GTAProcess_lVsMJHm6dg](https://github.com/jimathy/jim-mining/assets/82875923/17e47ba7-1031-4db7-96ff-d405c9cec822)

**Comment by Jxelsw** [comment]
![FiveM_b2699_GTAProcess_3qAdOSlTBu](https://github.com/jimathy/jim-mining/assets/82875923/ffeaaf50-36a2-4602-a78b-a3c4f253b79a)
![FiveM_b2699_GTAProcess_kThUOcgXjt](https://github.com/jimathy/jim-mining/assets/82875923/1acdd1bd-6a81-4e59-ae96-f0090d46ed37)
![FiveM_b2699_GTAProcess_hWuM9obzmP](https://github.com/jimathy/jim-mining/assets/82875923/6b2a1e2e-f2d0-4d5f-b22f-521de76bdfec)

![FiveM_b2699_GTAProcess_Opwg7FFFoO](https://github.com/jimathy/jim-mining/assets/82875923/d68e6330-31b4-4198-b26d-cb86c235bb82)

**Comment by Jxelsw** [comment]
> Yup I am also facing the same issue. ![image](https://user-images.githubusercontent.com/95373009/276572221-20859b4f-8721-429a-bf4c-1b8825273013.png)

Yes and the developer does nothing

**Comment by jimathy** [comment]
> > Yup I am also facing the same issue. ![image](https://user-images.githubusercontent.com/95373009/276572221-20859b4f-8721-429a-bf4c-1b8825273013.png)
> 
> Yes and the developer does nothing

:)

The issue isn't in the script my friend

The issue is its trying to load models from k4mb1's paid mlo and it can't find them.

So it doesn't make sense to pull the "dev" doesn't do anything when I can't fix your server finding loaded models.
