### ISSUE TITLE
shared and png issue

### ISSUE THREAD

**Issue by Andyauk** [jimathy/jim-mining#6]
['diamond_ring'] 
['goldchain'] 
you might want to change or let people know to remove the other instance of these two. as there in by default. 

And with your 10ct-gold-chain.png shouldn't it be 10kgoldchain.png

**Comment by jimathy** [comment]
to be honest it was left in by mistake, but doesn't cause any issues in the long run

**Comment by Andyauk** [comment]
> to be honest it was left in by mistake, but doesn't cause any issues in the long run

true buddy, keep up the great work

**Comment by jimathy** [comment]
I think I've also fixed the other issue.
